apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  labels:
    app: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: shubham310799/taskmanager-frontend
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_BASE_URL
              value: "taskmanager-api-service/api"
